### ISSUE TITLE
I get "Couldn't create font from data"

### ISSUE THREAD

**Issue by khaledannajar** [JZDesign/CustomFontSwiftUIExample#1]
in this code:

` guard let fontURL = bundle.url(forResource: fontName, withExtension: fontExtension),
           FileManager().fileExists(atPath: fontURL.path),
          let fontDataProvider = CGDataProvider(url: fontURL as CFURL),
          let font = CGFont(fontDataProvider) else {
              fatalError("Couldn't create font from data")
    }`

I tested the file path exists and still the initializer returns null
This returns true: FileManager().fileExists(atPath: fontURL.path)

Do you know the problem cause?

**Comment by khaledannajar** [comment]
It worked. My bad. I added only two files while the code was looking for 4 files. So adding the missing files did it.
Thanks for the great tutorial

**Comment by JZDesign** [comment]
Any time! Glad you got it working!
